algoritmo "COntador iteligente"
var

   ini , fin : inteiro

inicio

      escreva ("Contar de... ")
      leia (ini)
      escreva ("Até... ")
      leia (fin)

       se (ini < fin) entao
        enquanto ini <= fin faca
         escreva (" ...", ini )
         ini <- ini + 1
        fimenquanto
       senao
        enquanto fin <= ini faca
         escreva (" ...", ini )
         ini <- ini - 1
        fimenquanto
       fimse





fimalgoritmo